### ISSUE TITLE
File Missing

### ISSUE THREAD

**Issue by balamurugan19** [CKOTech/checkout-php-library#20]
I have got Fatal error for in checkout lib

Fatal error: Class 'CheckoutApi_Api' not found in com/checkout/helpers/ApiHttpClient.php on line 17

Need Solution for this  one

**Comment by n2oula** [comment]
Hello there,

Try to clone the library with the submodule by using the below command:
git clone --recursive https://github.com/CKOTech/checkout-php-library.git

**Comment by loranger** [comment]
I have the same issue.
I did install CheckOutAPI using composer (`require "checkout/checkout-php-api:dev-master"`) and don't want to split my libs outside composer.
@dhiraj-gangoosirdar-cko could you please upgrade the checkout-php-library dependancies ?
Thanks.

**Comment by fsalomon** [comment]
+1

**Comment by nicolas-maalouf-cko** [comment]
Please try the below to remove the mater branch library and install the updated one from our release/v1.2 branch:

composer remove checkout/checkout-php-api --update-with-dependencies
composer require "checkout/checkout-php-api:dev-release/v1.2"

Don't forget to include autoload.php file when you want to use the Checkout.com library:
If you're using Laravel:
include __DIR__.'/../vendor/checkout/checkout-php-api/autoload.php';

**Comment by fsalomon** [comment]
That did the trick, thanks!
