### ISSUE TITLE
Make errorCode accessible in exceptions

### ISSUE THREAD

**Issue by fsalomon** [CKOTech/checkout-php-library#32]
com\checkout\helpers\ApiHttpClient is throwing generic PHP exceptions.

Please throw a custom exception class instance instead so that I can access the errorCode and eventId in my exception handler.

**Comment by ravish-ramrakha-cko** [comment]
You can get error messages using the following codes:

if ($Api->getExceptionState()->hasError())
{
     $Api->getExceptionState()->getErrorMessage();
}

**Comment by fsalomon** [comment]
Error messages are for humans and might change. I need the error codes.

**Comment by nicolas-maalouf-cko** [comment]
@fsalomon this has been added in https://github.com/CKOTech/checkout-php-library/pull/38#event-613497640

When catching exceptions you can now use the below:

catch (com\checkout\helpers\ApiHttpClientCustomException $e) {
        echo 'Caught exception Message: ',  $e->getErrorMessage();
        echo 'Caught exception Error Code: ',  $e->getErrorCode();
        echo 'Caught exception Event id: ',  $e->getEventId();
    }
