### ISSUE TITLE
No possibility to create recurring payment with card id

### ISSUE THREAD

**Issue by maciejmiara** [CKOTech/checkout-php-library#45]
Your models doesn't support card id for recurring payments (no way to set it). It's strange, because payload mapper looks for card id and it is possible to include it in payload.

For now, only possibility supported by your models is to create recurring payment with full card details and I can't do that (no PCI compliance).

In class com\checkout\ApiServices\RecurringPayments\RequestModels\PlanWithChargeCreate there should be field $_cardId with correct getter and setter methods (like in com\checkout\ApiServices\Charges\RequestModels\CardIdChargeCreate )

Only solution for me is to prepare custom model, which will contain card id.

**Comment by nicolas-maalouf-cko** [comment]
@maciejmiara, we integrated the createPlanWithCardId and createPlanWithCardToken endpoints in the latest update. 
The old endpoint "createPlanWithCharge" has been renamed to "createPlanWithFullCard".

Please let us know if all works for you

**Comment by nicolas-maalouf-cko** [comment]
@maciejmiara we will be closing this issue.
Please feel free to get back to us for any inquiry.
