### ISSUE TITLE
\com\checkout\ApiServices\Charges\ChargeService::getChargeHistory() has a wrong PHPDoc result type

### ISSUE THREAD

**Issue by mage2pro** [CKOTech/checkout-php-library#50]
https://github.com/CKOTech/checkout-php-library/blob/7c9312e/com/checkout/ApiServices/Charges/ChargeService.php#L288

Should be ResponseModels\ChargeHistory, not ResponseModels\Charge

**Comment by nicolas-maalouf-cko** [comment]
Thank you for your feedback, this will be fixed in the next release
