### ISSUE TITLE
Missing com\checkout\ApiServices\Tokens\RequestModels\PaymentTokenUpdate class

### ISSUE THREAD

**Issue by elvenpath** [CKOTech/checkout-php-library#58]
This file was supposed to be present in my commit (which was merged into dev some weeks ago, #51), but cannot find it in any of the current branches. I do have it in my local repo.

It is used in the master branch in https://github.com/CKOTech/checkout-php-library/blob/master/com/checkout/ApiServices/Tokens/TokenService.php#L46

Let me know in what branch do you want to commit it.

**Comment by nicolas-maalouf-cko** [comment]
Hi @elvenpath , 

Please commit your changes to the [dev branch](https://github.com/CKOTech/checkout-php-library/tree/dev)

Thanks

**Comment by elvenpath** [comment]
merged
